[package]
name = "aggregator"
version = "0.1.0"
authors = ["Jan Tache <j.andreitabs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
serde_json = "1"
log = "0.4"
env_logger = "0.8"
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "postgres", "json", "offline" ] }
anyhow = "1"
